feat: update configuration and templates
- Added GitHub token support in .chezmoi.yaml.tmpl for authentication.
- Included Material Symbols fonts
- Enhanced wallpapers.yaml.tmpl with stripComponents for archive handling.
- Updated .chezmoiignore.tmpl to exclude waybar and swaync configurations.
- Modified executable_initial_boot script to check for wallpapers directory.
- Introduced variables.fish.tmpl to set XDG base directory environment variables.
- Adjusted waypaper config.ini to use state dir

diff --git a/home/dot_config/hypr/hyprland/scripts/executable_initial_boot b/home/dot_config/hypr/hyprland/scripts/executable_initial_boot
--- a/home/dot_config/hypr/hyprland/scripts/executable_initial_boot
+++ b/home/dot_config/hypr/hyprland/scripts/executable_initial_boot
@@ -4,9 +4,15 @@
 # Do not run it manually(it wont run though as long as the ".first_setup_done" exists)
 
 if [[ ! -f ~/.config/hypr/.first_setup_done ]]; then
-    sleep 1
+    sleep 2
     if command -v waypaper &>/dev/null; then
-        waypaper --random
+
+        if [[ ! -d "$HOME/Pictures/Wallpapers" ]]; then
+            notify-send "ERROR" "Wallpapers not found! Please create it at $HOME/Pictures/Wallpapers"
+            exit 1
+        fi
+
+        waypaper --folder "$HOME/Pictures/Wallpapers" --random
     fi
 
     # create the first setup done file
