feat: enhance OS identification in scripts
- Added get_os_id and get_os_name functions to retrieve OS information

diff --git a/home/.chezmoiscripts/linux/arch/run_once_before_02_packages.sh.tmpl b/home/.chezmoiscripts/linux/arch/run_once_before_02_packages.sh.tmpl
--- a/home/.chezmoiscripts/linux/arch/run_once_before_02_packages.sh.tmpl
+++ b/home/.chezmoiscripts/linux/arch/run_once_before_02_packages.sh.tmpl
@@ -23,6 +23,10 @@ if [[ "$(id -u)" -eq 0 ]]; then
   die "Do not run this script as root."
 fi
 
+if ! keep_sudo_alive; then
+  die "Failed to keep sudo alive"
+fi
+
 if [[ "${SKIP_PACKAGES:-0}" == "1" ]]; then
   log INFO "Skipping package installation"
   exit 0
@@ -137,18 +141,18 @@ if [[ $gpu_info == *"NVIDIA"* ]]; then
     nvidia_variant="nvidia-dkms"
   fi
 
-if [[ -f /etc/os-release ]]; then
-  # shellcheck source=/dev/null
-  source /etc/os-release
-  case "${ID:-}" in
-    cachyos|garuda)
-      log SKIP "Skipping NVIDIA variant selection on ${ID}"
-      ;;
-    *)
-      drivers+=("${nvidia_variant}")
-      ;;
-  esac
-fi
+  if os_id=$(get_os_id); then
+    case "$os_id" in
+      cachyos|garuda)
+        log SKIP "Skipping NVIDIA variant selection on $os_id"
+        ;;
+      *)
+        drivers+=("${nvidia_variant}")
+        ;;
+    esac
+  else
+    drivers+=("${nvidia_variant}")
+  fi
 
 fi
 
